### PR TITLE
[release-4.13] OCPBUGS-19825: Update staticpod file permissions to conform with CIS benchmarks

### PR DESCRIPTION
**Pull request by ardaguclu**
This PR is a manual cherry-pick of these 3 PRs;
* https://github.com/openshift/library-go/pull/1570
* https://github.com/openshift/library-go/pull/1536
* https://github.com/openshift/library-go/pull/1546

### CODE REVIEW

**Comment by ardaguclu** [comment]
/hold 
until it is verified

**Comment by ardaguclu** [comment]
Fake bumps prove that the patch works;
* https://github.com/openshift/cluster-etcd-operator/pull/1125 -> https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/1125/pull-ci-openshift-cluster-etcd-operator-release-4.13-e2e-aws-ovn-etcd-scaling/1706932645188866048
* https://github.com/openshift/cluster-kube-controller-manager-operator/pull/752 -> https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-kube-controller-manager-operator/752/pull-ci-openshift-cluster-kube-controller-manager-operator-release-4.13-e2e-aws-operator/1706931105090768896
* https://github.com/openshift/cluster-kube-apiserver-operator/pull/1558 -> https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-kube-apiserver-operator/1558/pull-ci-openshift-cluster-kube-apiserver-operator-release-4.13-e2e-gcp-operator/1706929342656811008
* https://github.com/openshift/cluster-kube-scheduler-operator/pull/497 -> https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-kube-scheduler-operator/497/pull-ci-openshift-cluster-kube-scheduler-operator-release-4.13-e2e-aws-ovn/1706928760458055680

**Comment by ardaguclu** [comment]
/hold cancel
@dgrisonnet could you PTAL?. Thanks.

**Review by dgrisonnet — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
