### PR TITLE
Make certrotation functions public

### PR DESCRIPTION
**Pull request by mhenriks**
Resurrecting #540 

Making these functions public so they can be useful for other projects.

### CODE REVIEW

**Comment by alromeros** [comment]
Hey @deads2k, could you take a look at this? We've been trying to make these functions public for some time since they could be useful for other projects (https://github.com/kubevirt/containerized-data-importer/issues/1097). Feel free to hold or close if necessary, thanks!

**Comment by akalenyu** [comment]
/cc @deads2k 
Hi! is this something that can be accepted?

**Comment by mhenriks** [comment]
Looks like this has been addressed here:  https://github.com/openshift/library-go/commit/434fa21f5e457d51f436c4b3804c7803db1da42d

**Pull request closed without merging**
