### PR TITLE
WRKLDS-1449: bump(k8s): update k8s.io/* dependencies to v1.31.1

### PR DESCRIPTION
**Pull request by atiratree**

### CODE REVIEW

**Comment by gallettilance** [comment]
Is there a reason this is still in WIP?

**Comment by tpantelis** [comment]
Is there an approximate ETA for this PR to land? This is blocking the https://github.com/stolostron/submariner-addon repo from bumping other dependencies.

**Comment by atiratree** [comment]
@tpantelis hopefully by the end of week, or beginning of the next week

**Comment by mzeevi** [comment]
We're also looking for this to get merged, any updates?

**Comment by atiratree** [comment]
https://github.com/openshift/api/pull/1983 https://github.com/openshift/client-go/pull/291 have been merged today

next one is this PR

cc @gallettilance @tpantelis @mzeevi

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
