### PR TITLE
Updating to the latest openshift/api

### PR DESCRIPTION
**Pull request by kwoodson**
Updating the openshift/api libraries.

### CODE REVIEW

**Comment by kwoodson** [comment]
@soltysh Here is the PR for the API only.  I also have the client-go PR here https://github.com/openshift/client-go/pull/194

**Comment by kwoodson** [comment]
Fixed the unit tests.

**Comment by kwoodson** [comment]
@soltysh @sttts @deads2k Could you please review this PR? I'd like to move forward with the API updates.

**Comment by deads2k** [comment]
/approve

update client-go after it merges.

**Comment by kwoodson** [comment]
Removing the client-go as per @deads2k request and will submit a separate PR with that update.

**Comment by kwoodson** [comment]
@deads2k Mind approving again. I misunderstood the comments from slack.

**Pull request merged**
