### PR TITLE
restrict the featuregate access API to enabled bool only

### PR DESCRIPTION
**Pull request by deads2k**
requires https://github.com/openshift/cluster-config-operator/pull/297 first

This further restricts usage of featuregates to have only a list and `Enabled`.  This prevents differentiated logic based on presence or absence in enabled/disabled list and forces usage of the openshift/api names since all other access panics.  This makes the code consistent and prevents "rogue" featuregates in our API.

/assign @JoelSpeed

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
/lgtm

**Comment by deads2k** [comment]
/hold

holding for prereqs

**Comment by deads2k** [comment]
proof in https://github.com/openshift/cluster-kube-controller-manager-operator/pull/732

**Comment by deads2k** [comment]
also proof in https://github.com/openshift/cluster-kube-apiserver-operator/pull/1487

**Comment by deads2k** [comment]
proof worked

/hold cancel

**Pull request merged**
