### PR TITLE
API-1835: Update the installer state controller to use Apply

### PR DESCRIPTION
**Pull request by p0lyn0mial**
proof pr at https://github.com/openshift/cluster-kube-apiserver-operator/pull/1746

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
/hold

holding off for a proof pr.

**Comment by deads2k** [comment]
/lgtm
/approve

be sure to check your proof to be sure we havne't lost conditions.  release the hold whenever you're ready.

**Comment by p0lyn0mial** [comment]
> be sure to check your proof to be sure we havne't lost conditions. release the hold whenever you're ready.

checked the must-gather from the [run](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cluster-kube-apiserver-operator/1746/pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-gcp-operator/1839667752529301504/artifacts/e2e-gcp-operator/gather-must-gather/artifacts/). All `3` conditions are present:
```
...
 - lastTransitionTime: "2024-09-27T14:32:44Z"
    status: "False"
    type: InstallerPodContainerWaitingDegraded
  - lastTransitionTime: "2024-09-27T14:32:44Z"
    status: "False"
    type: InstallerPodNetworkingDegraded
  - lastTransitionTime: "2024-09-27T14:32:44Z"
    status: "False"
    type: InstallerPodPendingDegraded
  - lastTransitionTime: "2024-09-27T14:33:13Z"
    status: "False"
...
```

**Pull request merged**
