### PR TITLE
Switch openshift/library-go to go1.11

### PR DESCRIPTION
**Pull request by soltysh**
/assign @deads2k 
Requires https://github.com/openshift/release/pull/3418

### CODE REVIEW

**Comment by sttts** [comment]
/lgtm
/approve

Waiting for release PR.

**Comment by soltysh** [comment]
Waiting for https://github.com/openshift/release/pull/3452 to be effective.

**Comment by deads2k** [comment]
saw a gofmt blip.  I suspect this.

/test all

**Comment by soltysh** [comment]
Bumped memory in https://github.com/openshift/release/pull/3453
/retest

**Pull request merged**
