### PR TITLE
OCPBUGS-7190: ldapquery: expect an LDAP client with an active connection

### PR DESCRIPTION
**Pull request by stlaz**
The LDAP querying functions were being misused by calling them in a for loop, which has a potential of generating a needless amount of connection/bind attempts.

Make the user supply an LDAP client with an active connection in order to enforce proper behavior.

/cc @deads2k @ibihim

### CODE REVIEW

**Comment by stlaz** [comment]
/hold
@ibihim to review but I'd like @deads2k to approve

**Review by ibihim — APPROVED** [review]
/lgtm

**Comment by zhouying7780** [comment]
Done pre-merge test . no issue found . see details from the bug .

**Pull request merged**
