### PR TITLE
certgraphanalysis: include ondisk certs in ElideProxyCADetails

### PR DESCRIPTION
**Pull request by vrutkovs**
Include several ondisk certs in ElideProxyCADetails to mark them as trusted CA bundles

Tested in https://github.com/openshift/origin/pull/28868

### CODE REVIEW

**Comment by dusk125** [comment]
non-binding lgtm

**Comment by deads2k** [comment]
someday it would be nice to pay down debts, but this is better than where we're currently at

/approve
delegating to @dusk125

**Pull request merged**
