### PR TITLE
NO-JIRA: add test-e2e-monitoring placeholder test

### PR DESCRIPTION
**Pull request by p0lyn0mial**
should unblock https://github.com/openshift/library-go/pull/1823

it works on my local machine:
```
make test-e2e-monitoring
go test -mod=vendor -race ./test/e2e-monitoring/...
ok  	github.com/openshift/library-go/test/e2e-monitoring	(cached)
```

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
OK, `ci/prow/e2e-monitoring ` run `TestResourceVersionApplication`.

**Comment by dgrisonnet** [comment]
I think we should activate the test-e2e-monitoring rule in https://github.com/openshift/library-go/pull/1823 instead.

**Comment by p0lyn0mial** [comment]
/close

pulled into https://github.com/openshift/library-go/pull/1823

**Pull request closed without merging**
