### PR TITLE
API-1783: bump(k8s): Update k8s to 1.30

### PR DESCRIPTION
**Pull request by dinhxuanvu**
1. Rebase k8s to 1.30

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
Updated to v1.30.0-rc.0

**Comment by dinhxuanvu** [comment]
Will squash the commits if needed later on. Multiple commits are easier to review the changes for now.

**Comment by soltysh** [comment]
/hold
this should not merge into 4.16 accidentally

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
