### PR TITLE
Bug 1907373: kube 1.20.0

### PR DESCRIPTION
**Pull request by tnozicka**
Require:
- [x] https://github.com/openshift/api/pull/789
- [x] https://github.com/openshift/client-go/pull/172

/cc @soltysh

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
@tnozicka please wait until https://github.com/openshift/library-go/pull/943 merges

it requires  follow up PRs to our operators which you are going to provide since you are rebasing. thanks !

**Comment by p0lyn0mial** [comment]
> @tnozicka please wait until #943 merges
> it requires follow up PRs to our operators which you are going to provide since you are rebasing. thanks !

never mind, @sttts  said we can remove it later.

**Comment by soltysh** [comment]
@p0lyn0mial you can continue with your PR, this is not going to merge until we're close to landing k8s bump, we already have temporary branches for the bumps

**Review by soltysh — APPROVED** [review]
/lgtm

I'm manually adding approve label since this was extensively tested already in several operators, oc and k8s bump

**Pull request merged**
