### PR TITLE
refactor static pod controller building

### PR DESCRIPTION
**Pull request by deads2k**
```go
staticPodController, err = NewBuilder().
    WithEvents().
    WithInstaller().
    WithPruning().
    WithVersioning().
    ToControllers()
```

/assign @sttts

### CODE REVIEW

**Comment by sttts** [comment]
Lgtm. Do you have a PR proving it works?

**Comment by deads2k** [comment]
> Lgtm. Do you have a PR proving it works?

no, but it was all straight moves

**Comment by deads2k** [comment]
pull here https://github.com/openshift/cluster-kube-controller-manager-operator/pull/164

**Comment by deads2k** [comment]
@ravisantoshgudimetla I think you're the rigth ravig.  This will get our arg list under contrtol

**Comment by deads2k** [comment]
proof pull is green.

**Pull request merged**
