### PR TITLE
chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

### PR DESCRIPTION
**Pull request by Juneezee**
Currently we are using two YAML packages:
1. `github.com/ghodss/yaml v1.0.0`
2. `sigs.k8s.io/yaml v1.3.0`

The `github.com/ghodss/yaml` package is no longer actively maintained. `sigs.k8s.io/yaml` is a permanent fork of `github.com/ghodss/yaml`. It is actively maintained by Kubernetes SIG, and also widely used in K8s projects.

The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, but `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. Changes can be seen here [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), mostly bug fixes.

### CODE REVIEW

**Comment by Juneezee** [comment]
/assign @soltysh

Hi, sorry for the explicit mention. I would be grateful if you could take some time to review the changes and provide me with your feedback. If there are any specific concerns or questions you have about the changes, I am more than willing to help address them. Thank you :smile:

**Comment by Juneezee** [comment]
/assign @deads2k
/assign @ingvagabund 

Hi, I would be grateful if you could take some time to review the changes and provide me with your feedback. If there are any specific concerns or questions you have about the changes, I am more than willing to help address them. Thank you :smile:

**Comment by ingvagabund** [comment]
sigs.k8s.io/yaml was forked ~6 years ago. The original repo merged only comments, test changes and a new function. sigs.k8s.io/yaml continued to develop the code. There's a bunch of vendored deps updates. With creating yaml.v3. Looks like it all looks good.

**Comment by Juneezee** [comment]
@deads2k Friendly ping :smile:

**Comment by Juneezee** [comment]
@deads2k Friendly ping :smile:

**Comment by Juneezee** [comment]
Rebased to resolve conflicts

image

**Comment by Juneezee** [comment]
@deads2k @ingvagabund Any idea on why the bot is not applying the label? The bot seems to be acting weird today :thinking:

**Pull request merged**
