### PR TITLE
installer: QoS class guaranteed with 100MB

### PR DESCRIPTION
**Pull request by sttts**
We measured 25MB RSS. So 100MB should be safe to have some room to breath and not too big.

### CODE REVIEW

**Comment by deads2k** [comment]
that's v1alpha1, you also need to get the bindata one I linked in the other pull (the v1 flavor)

**Comment by deads2k** [comment]
we left the old for an orderly transition.  I'm ok deleting that now too.

**Comment by sttts** [comment]
@deads2k removed v1alpha1staticpods and updated v1 variant

**Pull request merged**
