### PR TITLE
image: introduce dockerclient and registry client

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm

pending green https://github.com/openshift/origin/pull/23019

/hold

holding for proof

**Comment by mfojtik** [comment]
@deads2k weird... i pruned the vendor/ dir yet still getting a diff there for distribution....

**Comment by deads2k** [comment]
With a clean glide cache, I get the same result.  I've had trouble with verify-deps in the past.  We'll merge this.

**Pull request merged**
