### PR TITLE
Add codegen-crds targets

### PR DESCRIPTION
**Pull request by tnozicka**
/cc @damemi @soltysh @sttts 

build on top of @damemi's https://github.com/openshift/library-go/pull/521

### CODE REVIEW

**Comment by damemi** [comment]
This looks good to me, but CI is still failing on (I think) that test where we expect an error: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_library-go/526/pull-ci-openshift-library-go-master-verify-alpha-build-machinery/1368#0:build-log.txt%3A435 points to this line: https://github.com/openshift/library-go/pull/526/files#diff-64b9efa1ab03ac55fe2aa1425d910d08R35

**Comment by tnozicka** [comment]
green now - fixed those false positives from older version on centos

**Comment by damemi** [comment]
Changes added in https://github.com/openshift/cluster-kube-apiserver-operator/pull/568 and tested manually, seems to work! Thanks for the help @tnozicka 
/lgtm

**Comment by damemi** [comment]
/hold
one sec, verify seems touchy

**Pull request merged**
