### PR TITLE
Migrate csi deployment to use generic deployment

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
The 2 commits in this PR are picked from #1095 to make sure that the storage team is not blocked on static pod guard controller for the PR.

### CODE REVIEW

**Review by ravisantoshgudimetla — COMMENTED** [review]
/hold

for @jsafrane and @bertinatto to give final LGTMs.

**Comment by deads2k** [comment]
I like the direction here.  I'll leave lgtm with storage.

/approve
/assign @jsafrane @bertinatto 

Please ensure that a proof PR passes for storage (link here) and I'd like this to merge before the refactors from storage in these controllers.

**Comment by ravisantoshgudimetla** [comment]
https://github.com/openshift/aws-ebs-csi-driver-operator/pull/128 - Proof [PR](https://github.com/openshift/aws-ebs-csi-driver-operator/pull/128) with changes from this PR

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
