### PR TITLE
Bump openshift/api to pick up capabilities

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
It will pick up the API changes required for capabilities

    Generated with:

      $ go get github.com/openshift/api@d7c10d0b647e4c1a82c800556984e01f637577fd
      $ go mod tidy
      $ go mod vendor
      $ git add -A go.* vendor

    using:

      $ go version
      go version go1.17.3 linux/amd64

    This will pick up the new ClusterVersion capabilities stuff.

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by wking** [comment]
openshift/api@7e3ffb09acc is enough to get openshift/api#1106 for #1333.  But there are a bunch of changes since then, and we might as well bring those in too:

```console
$ git --no-pager log --oneline --first-parent 7e3ffb09acc..origin/master
d7c10d0b (HEAD -> master, wking/master, origin/release-4.12, origin/release-4.11, origin/master, origin/HEAD) Merge pull request #1126 from QiWang19/mirrorset
abf6417c [OCPCLOUD-1422] machine-api: azureprovider: add ultra disk support (#1119)
c21df433 Merge pull request #1134 from JoelSpeed/fix-optional-subnet
94bdffb4 Merge pull request #1112 from JoelSpeed/control-plane-machine-set
654ca07c Merge pull request #1131 from JoelSpeed/fix-partition-number-tag
5170e8de Merge pull request #1125 from honza/cbo-capability
7aa5824a Merge pull request #1123 from soltysh/bug2054693
24043075 Merge pull request #1107 from harche/node_object
354aa98a Merge pull request #1091 from JoelSpeed/mapi-aws-placement-groups
309b7ebb Merge pull request #1121 from bparees/console
271bd7e1 Merge pull request #1122 from gcs278/master
aa98df52 Merge pull request #1109 from bparees/compat
b632c5fc (origin/pr/1111) Merge pull request #1115 from bertinatto/god-help-us
```

**Comment by LalatenduMohanty** [comment]
> [openshift/api@7e3ffb09acc](https://github.com/openshift/api/commit/7e3ffb09acc) is enough to get [openshift/api#1106](https://github.com/openshift/api/pull/1106) for #1333. But there are a bunch of changes since then, and we might as well bring those in too:

@wking Updated the PR to latest API commit

**Review by wking — APPROVED** [review]
/lgtm

**Pull request merged**
