### PR TITLE
factory/base_controller: properly synchronize runPeriodicalResync function

### PR DESCRIPTION
**Pull request by p0lyn0mial**
found in https://github.com/openshift/library-go/pull/1535#discussion_r1211877928

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
I am going to open a prove PR :) (just in case)

**Comment by p0lyn0mial** [comment]
> a proof PR https://github.com/openshift/cluster-kube-apiserver-operator/pull/1508

the proof PR lgtm, ptal at this PR, thanks.

**Comment by p0lyn0mial** [comment]
/assign @mfojtik 

for approval

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
