### PR TITLE
revert of #926: provides DefaultClientDialer that returns a network dialer with default options sets

### PR DESCRIPTION
**Pull request by p0lyn0mial**
https://github.com/openshift/library-go/pull/943 was meant as a temporary solution for detecting broken persistent connections.

This mechanism was replaced by HTTP/2 connection health check which is now part of `http.Transport` and will be applied by default to all clients created via `client-go` library.

### CODE REVIEW

**Comment by sttts** [comment]
better call it "revert of ..."

**Comment by p0lyn0mial** [comment]
> better call it "revert of ..."

done.

**Comment by sttts** [comment]
/hold

until 1.20 prebase branches go merged into master

**Pull request closed without merging**
