### PR TITLE
Symlink kube

### PR DESCRIPTION
**Pull request by tnozicka**
/cc @mfojtik @soltysh @deads2k

### CODE REVIEW

**Comment by tnozicka** [comment]
This is really just a bug fix to do what hacks in origin did.

ref: https://github.com/openshift/kubernetes-apiserver/pull/1#issuecomment-519489336

**Comment by mfojtik** [comment]
I'm not sure we want to do this anymore, lets wait for @deads2k and @sttts to be back and talk about what we want to do. This can wait.

**Comment by sttts** [comment]
Staging in library-go???? 😱 Let's close this before anybody merges.

**Comment by tnozicka** [comment]
> Staging in library-go???? scream Let's close this before anybody merges.

it is in the very specific section of openshift dependency management. If you vendor the whole kubernetes I think the correct path is to symlink staging

@deads2k ?

**Comment by sttts** [comment]
Do we vendor k/k here? We should not.

**Comment by sttts** [comment]
It is about the build system. But we certainly won't test-vendor k/k here in a library repo. Create a test repo and check it out in some CI test instead if we want to test it continuously.

**Comment by tnozicka** [comment]
> Do we vendor k/k here? We should not.

it is for build machinery, not library-go

**Comment by sttts** [comment]
> it is for build machinery, not library-go

Still. 2 million lines of (dead) code is a nogo. Create a test repo and wire that into the CI tests here.

**Comment by tnozicka** [comment]
Unit tests are conventionally located at the same repo. This is just another reason that shows buil-machinery should live in it's own repo.

**Comment by tnozicka** [comment]
I guess I could wire it so the example vendor isn't committed (and does live restore), I agree we don't wan't to pull it in and commit into deps. Doesn't the `--strip-vendor` prune those though?

@sttts I don't think I've head your opinion on the symlinking itself

**Comment by sttts** [comment]
Not committing it sounds like a solution. Would be ok with that.

`--strip-vendor` strips it, but you still get a huge repository.

**Pull request closed without merging**
