### PR TITLE
[release-4.12] OCPBUGS-19837: Update staticpod file permissions to conform with CIS benchmarks

### PR DESCRIPTION
**Pull request by ardaguclu**
This PR is a manual cherry-pick of these 3 PRs;
* https://github.com/openshift/library-go/pull/1570
* https://github.com/openshift/library-go/pull/1536
* https://github.com/openshift/library-go/pull/1546

### CODE REVIEW

**Comment by ardaguclu** [comment]
/hold
until it is verified

**Comment by ardaguclu** [comment]
/hold cancel
@dgrisonnet could you PTAL?. Thanks.

**Review by dgrisonnet — APPROVED** [review]
/lgtm
/approve

**Comment by ardaguclu** [comment]
@p0lyn0mial would you mind tagging this patch, when you have a chance? - apparently you are the only approver in this area for 4.12. Thanks.

**Pull request merged**
