### PR TITLE
support CRDs at v1 throughout the apply stack

### PR DESCRIPTION
**Pull request by deads2k**
1.  automatic informers get wired into the controller and the cache waiting
1. allow static resource management of CRDs

### CODE REVIEW

**Comment by sttts** [comment]
What is related to CRD v1? Looks like this mangles lots of changes? Can you document in the PR description why the other things are done?

**Comment by deads2k** [comment]
> What is related to CRD v1? Looks like this mangles lots of changes? Can you document in the PR description why the other things are done?

I'll rebase once we finish stepping through.

**Comment by deads2k** [comment]
builds on https://github.com/openshift/library-go/pull/673

**Comment by sttts** [comment]
Second commit lgtm.

**Comment by deads2k** [comment]
both commits reviewed now.

**Pull request merged**
