### PR TITLE
WRKLDS-1078: Revision controller not found no new revision 4.15

### PR DESCRIPTION
**Pull request by ingvagabund**
Backporting https://github.com/openshift/library-go/pull/1682 to 4.15

### CODE REVIEW

**Comment by ingvagabund** [comment]
/hold

until https://github.com/openshift/cluster-kube-scheduler-operator/pull/537 goes green

**Comment by deads2k** [comment]
/lgtm
/approve

/hold

please get it vendored into etcd, kas, kcm, and ks in master before releasing the hold

**Pull request merged**
