### PR TITLE
fix: should judge whether updateErr is nil

### PR DESCRIPTION
**Pull request by dk-lockdown**
same as title.

### CODE REVIEW

**Review by kikisdeliveryservice — COMMENTED** [review]
I'm not super familiar with this repo but seems like a reasonable fix.  In the worst case this would be using err from line 114. :grimacing:  

Similar issue on line 146 where it's referencing a generic err instead of createErr https://github.com/openshift/library-go/blob/84d884f4c9f6d5f3f38c4f4e6bf3305143f23c4b/pkg/operator/status/status_controller.go#L146

/ok-to-test

**Comment by dk-lockdown** [comment]
If there is no status update permission, the update operation will always fail, but using err judgment will make the program continue to execute. I think  line 146 should use `createErr instead of `err`, otherwise, `syncCtx.Recorder()` will not record the correct error output

**Review by kikisdeliveryservice — COMMENTED** [review]
/lgtm

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
